# Generated by Django 4.1.7 on 2023-04-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revistas',
            old_name='id_livro',
            new_name='id_revista',
        ),
    ]
