# Generated by Django 4.2 on 2023-04-03 18:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolate',
            fields=[
                ('id_chocolate', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=300)),
                ('Preço', models.CharField(max_length=300)),
                ('validade', models.IntegerField()),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
    ]
