# Generated by Django 4.1.7 on 2023-04-01 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enciclopedias',
            fields=[
                ('id_enciclopedias', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=300)),
                ('lancamento', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('paginas', models.IntegerField()),
                ('editora', models.CharField(max_length=300)),
                ('criador', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
