# Generated by Django 4.1.7 on 2023-04-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enciclopedias',
            old_name='criador',
            new_name='criado',
        ),
    ]
