# Generated by Django 4.1.7 on 2023-04-01 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id_livro', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=300)),
                ('lancamento', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('pagginas', models.IntegerField()),
                ('editora', models.CharField(max_length=300)),
                ('criado', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
