# Generated by Django 4.1.7 on 2023-04-01 15:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='pagginas',
            new_name='paginas',
        ),
        migrations.AlterField(
            model_name='livros',
            name='id_livro',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
