# Generated by Django 4.1.7 on 2023-04-01 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_rename_criado_livros_criador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='criador',
            new_name='criado',
        ),
    ]
